the implementation of Milestone 2.
danielkrizian/helm-q.el pull request #2
Opened 2020-06-30 09:12 UTC by jingtaozf

2020-06-30 21:01 UTC, danielkrizian requested changes
It's an excellent first iteration! only two things to look at (plus below two suggested edits):

- [x] 1. [major] from [the mockup](https://docs.google.com/spreadsheets/d/14f2LBU2r__dJkpx5hZBJyuRy94wvKNatSBkw-r8CJhQ/edit#gid=0), can we include also cells B3 / B8:B9 as additional lines of each selection candidate, making each candidate a multiline entity? (e.g. like `helm-org-rifle`). The search pattern would be highlighted in bold within that additional context (see the mockup)

- [x] 2. [minor] a potential bug/unexpected result: try searching for pattern "name" or "namea". the results are unexpected:
UPDATE: seems like fuzzy matching, although the exact behavior is not clear. e.g. "AMALYTICS" does not match "ANALYTICS" despite this string pair seems less dissimilar than "name" vs "emea"
![image](https://user-images.githubusercontent.com/2865860/86175357-15a70580-bb1b-11ea-834d-bf9966bb1246.png)
![image](https://user-images.githubusercontent.com/2865860/86175385-248db800-bb1b-11ea-8f84-0bd114eace42.png)
![image](https://user-images.githubusercontent.com/2865860/86232258-943b8b80-bb8b-11ea-8050-7045e8a1b627.png)

2020-06-30 21:01 UTC, danielkrizian commented on helm-q.el
> +          (cdr (assoc 'service instance))))
```suggestion
(defun helm-q-instance-display-string (instance)
  "Argument INSTANCE: one instance."
  (format "%s %s %s %s"
          (cdr (assoc 'address instance))
          (cdr (assoc 'service instance))
          (cdr (assoc 'env instance))
          (cdr (assoc 'region instance))))
```

2020-06-30 21:01 UTC, danielkrizian commented on helm-q.el
> +  ;; a list whoise members are `(DISPLAY . REAL)' pairs.
```suggestion
  ;; a list whose members are `(DISPLAY . REAL)' pairs.
```

2020-07-01 01:45 UTC, jingtaozf commented on helm-q.el
> +          (cdr (assoc 'service instance))))
it's ok.:-)

2020-07-01 01:45 UTC, jingtaozf commented on helm-q.el
> +  ;; a list whoise members are `(DISPLAY . REAL)' pairs.
Thanks.

2020-07-02 06:50 UTC, danielkrizian commented
thanks for the multi-line support. the context is displayed largely as expected. one improvement:

- [ ] [major] when displaying columns of a table, currently the context does not display the associated table:
![image](https://user-images.githubusercontent.com/2865860/86323567-f8665a00-bc34-11ea-8aed-9e9021e104e8.png)
 is it possible to also show table in which the column is defined? it's a hierarchical relationship. one way of displaying that relationship is to collapse the hierarchy using dot `.` separator. The context would then show: ... `Column:'trade.price'`. but please feel free to suggest other possibly better ways

2020-07-02 06:55 UTC, jingtaozf commented
I have added table name in the display of column.

2020-07-02 08:54 UTC, merged